apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator-image-updater
  namespace: openshift-operators
spec:
  channel: latest # TODO: Set actual value
  installPlanApproval: Automatic # TODO: Set actual value
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: ARGOCD_IMAGE_UPDATER_ENABLED
        value: "true" # TODO: Set actual value
