apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# ArgoCD の HA 構成を有効化する
# Application Controller と Redis が複数レプリカで動作する

patches:
  - target:
      kind: ArgoCD
      name: argocd
    patch: |-
      - op: replace
        path: /spec/ha
        value:
          enabled: true
      - op: replace
        path: /spec/controller/sharding
        value:
          enabled: true
          replicas: 2
