apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s:
      retention: 15d # TODO: Set actual value
      resources:
        requests:
          cpu: 200m # TODO: Set actual value
          memory: 2Gi # TODO: Set actual value
        limits:
          cpu: "2" # TODO: Set actual value
          memory: 8Gi # TODO: Set actual value
      volumeClaimTemplate:
        spec:
          storageClassName: gp3-csi # TODO: Set actual value
          resources:
            requests:
              storage: 50Gi # TODO: Set actual value
    alertmanagerMain:
      resources:
        requests:
          cpu: 50m # TODO: Set actual value
          memory: 128Mi # TODO: Set actual value
        limits:
          cpu: 500m # TODO: Set actual value
          memory: 512Mi # TODO: Set actual value
