apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-viewer-idp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-viewer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: idp-developers # TODO: Set actual value
