apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: openshift-gitops
spec:
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    route:
      enabled: true
      tls:
        termination: reencrypt
    service:
      type: ""
  controller:
    appSync: 30s
    processors: {}
    sharding: {}
  ha:
    enabled: false
  notifications:
    enabled: true
  monitoring:
    enabled: false
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac:
    defaultPolicy: role:admin
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  resourceExclusions: |
    - apiGroups:
        - tekton.dev
      clusters:
        - '*'
      kinds:
        - TaskRun
        - PipelineRun
  applicationSet:
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  redis: {}
  repo: {}
  initialSSHKnownHosts: {}
  tls:
    ca: {}
