apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets-operator
  annotations:
    # IRSA Role ARN はクラスタ overlay でパッチすること
    eks.amazonaws.com/role-arn: "PLACEHOLDER"
