apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh
  namespace: rhdh
spec:
  channel: fast
  installPlanApproval: Automatic # TODO: Set actual value
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
