apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: external-secrets-operator
  namespace: openshift-operators
spec:
  resources:
    limits:
      cpu: 500m # TODO: Set actual value
      memory: 512Mi # TODO: Set actual value
    requests:
      cpu: 100m # TODO: Set actual value
      memory: 128Mi # TODO: Set actual value
