apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhdh-github-app
  namespace: rhdh
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rhdh-github-app
    deletionPolicy: Retain
  data:
    - secretKey: GITHUB_APP_ID
      remoteRef:
        key: openshift/rhdh/github-app
        property: appId
    - secretKey: GITHUB_APP_CLIENT_ID
      remoteRef:
        key: openshift/rhdh/github-app
        property: clientId
    - secretKey: GITHUB_APP_CLIENT_SECRET
      remoteRef:
        key: openshift/rhdh/github-app
        property: clientSecret
    - secretKey: GITHUB_APP_PRIVATE_KEY
      remoteRef:
        key: openshift/rhdh/github-app
        property: privateKey
