apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: ArgoCD
      name: openshift-gitops
    patch: |-
      - op: add
        path: /spec/notifications
        value:
          enabled: true
