apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# ArgoCD Notifications を有効化し、Sync 結果の通知を送信できるようにする

patches:
  - target:
      kind: ArgoCD
      name: argocd
    patch: |-
      - op: replace
        path: /spec/notifications
        value:
          enabled: true
