apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-custom-resources
  labels:
    app.kubernetes.io/part-of: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-custom-resources
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: openshift-gitops