apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-custom-resources
  labels:
    app.kubernetes.io/part-of: argocd
rules:
  # Quay Operator
  - apiGroups:
      - quay.redhat.com
    resources:
      - quayregistries
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # RHACS (StackRox) Operator
  - apiGroups:
      - platform.stackrox.io
    resources:
      - centrals
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # RHDH (Backstage) Operator
  - apiGroups:
      - rhdh.redhat.com
    resources:
      - backstages
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # RHTAS (Trusted Artifact Signer) Operator
  - apiGroups:
      - rhtas.redhat.com
    resources:
      - securesigns
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # RHTPA (Trusted Profile Analyzer) Operator
  - apiGroups:
      - rhtpa.io
    resources:
      - trustedprofileanalyzers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete